name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Cambia "main" si tu rama principal tiene otro nombre
  workflow_dispatch: # Permite ejecutar el flujo manualmente desde GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Verificar el repositorio (checkout)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Asegúrate de usar la misma versión que tu proyecto

      # 3. Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Desplegar a Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Secreto para autenticar en Firebase
        run: |
          firebase deploy --only hosting --project default
